# Generated by Django 4.2.6 on 2023-10-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra large'), ('XXL', 'Double extra large')], default='M', max_length=10),
        ),
    ]
