# Generated by Django 4.2.6 on 2024-02-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
