# Generated by Django 4.2.6 on 2023-10-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sizechoice_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL'), ('Double Extra Large', 'XXL')], default='M', max_length=30),
        ),
        migrations.DeleteModel(
            name='SizeChoice',
        ),
    ]
