# Generated by Django 4.2.6 on 2024-02-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, default='1989-1-1'),
            preserve_default=False,
        ),
    ]
