# Generated by Django 4.2.6 on 2024-02-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='otp_expiry_time',
        ),
    ]
