# Generated by Django 4.2.6 on 2023-10-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_product_size_sizes_colors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name_plural': 'Sizes'},
        ),
    ]
