# Generated by Django 4.2.6 on 2023-10-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_colors_color_alter_sizes_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='size',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
