# Generated by Django 4.2.6 on 2023-11-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_colors_color_alter_sizes_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizes',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
