# Generated by Django 4.2.6 on 2023-11-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_product_color'),
    ]

    operations = [
    ]
