# Generated by Django 4.2.6 on 2023-11-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_category_productsize_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
