# Generated by Django 4.2.6 on 2023-11-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_productsize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
