# Generated by Django 4.2.6 on 2023-11-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inside_image',
            field=models.ImageField(default='', upload_to='products/'),
        ),
    ]
