# Generated by Django 4.2.6 on 2023-11-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_product_inside_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inside_image',
        ),
    ]
