# Generated by Django 4.2.3 on 2023-12-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_product_inside_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
